### ISSUE TITLE
Inconsistent idea project configuration

### ISSUE THREAD

**Issue by rtaupe** [alpha-asp/Alpha#153]
Opening the existing project configuration from `.idea` with IntelliJ IDEA shows some errors: Files `.idea/modules/alpha.iml`, `.idea/modules/alpha_test.iml`, and `.idea/modules/alpha_main.iml` do not exist.

So the project configuration in `.idea` is inconsistent and should either be made consistent or removed from the repository.

**Comment by rtaupe** [comment]
@lorenzleutgeb can you help, please?

According to [this article](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839), `.iml` and `.idea/modules.xml` files do not have to be shared for gradle projects, since they "will be generated on import". However, when I try to import the gradle project to IntelliJ IDEA, it tells me that "The project file '[...]\Alpha\.idea' already exists. Would you like to overwrite it?".

In our case, the `.iml` files are not under version control, but `.idea/modules.xml` is.

Also, why did you split the project up into a _main_ and a _test_ module? As far as I can see (but I am a beginner with IDEA), this is not necessary because you can just designate the corresponding source folders as main or test (or generated) source folders within one module.

**Comment by rtaupe** [comment]
On a related note:
The file [.idea/misc.xml](https://github.com/alpha-asp/Alpha/blob/master/.idea/misc.xml) is under version control. In it, the name of the JDK used for building is fixed to the value `1.8`, which is in conflict with the fact that I am currently using version `11`.
Apparently, [OpenJDK 8](https://jdk.java.net/8/) is not available for Windows, so I cannot (easily) switch to JDK 1.8 (since, AFAIK, Java 8 versions released after January 2019 may not be used within businesses). What do you @lorenzleutgeb @AntoniusW think of upgrading to 11 (or 12)?

**Comment by lorenzleutgeb** [comment]
#### Regarding `.idea`

I acknowledge that there's a problem and that it is a long standing issue. I'll look into it.

#### Regarding the Java version to use
I am using 12 locally, for Alpha and for other projects. Just recently (in #176) I updated the list of versions we test against and also tried to establish a guideline going forward. So if "upgrading" means "installing and using for development locally", then sure, I am already doing that.

However if "upgrading" also means bumping [`(source|target)Compatibility`](https://github.com/alpha-asp/Alpha/blob/c50fb06669d4b9fe76bb876fc3e2dc2b72795298/build.gradle#L12-L13), then this opens the door to backward-incompatible changes to Alpha, and we have to be a bit more careful with these parameters. I would like to suggest the next version to be 11 (since it is an LTS release). It really [sounds like Java 8 is being phased out](https://www.oracle.com/technetwork/java/java-se-support-roadmap.html), so from my point of view we can make that change any time.

**Comment by rtaupe** [comment]
@lorenzleutgeb 

**Regarding `.idea`**
Thanks! :)

**Regarding the Java version to use**
No, I am not proposing to change the compatibility version, it should stay at `1.8`. I´d merely like to change the `project-jdk-name` from `1.8` to `11` in `misc.xml`. How are you using JDK 11 locally without running into versioning issues with this configuration file?

**Comment by lorenzleutgeb** [comment]
> How are you using JDK 11 locally without running into versioning issues with this configuration file?

I don't. I keep the version that works for me locally in my `git stash`.

**Comment by lorenzleutgeb** [comment]
> Also, why did you split the project up into a main and a test module? As far as I can see (but I am a beginner with IDEA), this is not necessary because you can just designate the corresponding source folders as main or test (or generated) source folders within one module.

This was done automatically by IntelliJ. The convention is to have one IntelliJ module per Gradle source set, so this is what the Gradle plugin does. See:
 - https://stackoverflow.com/questions/37018567
 - https://stackoverflow.com/questions/36372571
