### ISSUE TITLE
Command-line interface should provide option to choose branching heuristic

### ISSUE THREAD

**Issue by rtaupe** [alpha-asp/Alpha#18]
At the moment, DefaultSolver supports two branching heuristics (see 5a50abae61517e6a5b92ce655cabb784d1dca418), a number which might even increase in the future. Therefore, the command-line interface should provide an option to choose the heuristic(s).

**Comment by AntoniusW** [comment]
This is a good idea. In the future there probably will be several more options required, so we should introduce a common style for setting heuristics-related parameters.

One such parameter, I would like to see, is to turn off any uses of random() inside the heuristics, so that the solving process is completely deterministic. This is extremely helpful during debugging.

**Comment by flowlo** [comment]
I fully agree to the above.

Another attempt to tackle randomness is to have a well-defined source of randomness in our code base (we should have this independently of any CLI params). This would allow us to set the seed for randomness at a single place. A command line option to "disable" randomness would then just use a fixed seed.

This way no code that "uses randomness" needs to change, but we could "disable randomness" very easily.
