### ISSUE TITLE
NoGoods are counted multiple times if they are stored multiple times

### ISSUE THREAD

**Issue by rtaupe** [alpha-asp/Alpha#238]
It may happen that the same nogood is added to the `NoGoodStore` multiple times.
Examples:
 * In `HanoiTowerTest#testSimple` on the `add_simple_completion` branch, the nogood `{ +19 +34 +49 +64 +79 +94 +109 +124 +139 +235 } = {+(noMove(0, 1)), +(noMove(0, 2)), +(noMove(0, 3)), +(noMove(0, 4)), +(noMove(0, 5)), +(noMove(0, 6)), +(noMove(0, 7)), +(noMove(0, 8)), +(noMove(0, 9)), +(diskMoved(0))}` is added twice. The first time it is created by `DefaultSolver#justifyMbtAndBacktrack`, the second time from `DefaultSolver#noGoodFromJustificationReasons`.
  * In `DefaultSolver#addAndBackjumpIfNecessary`, there is a loop that (potentially) adds the same nogood again and again.

Since `NoGoodStoreAlphaRoaming#add` does not check for uniqueness of the nogood's ID (related issue: #87), the same nogood is then counted multiple times by `NoGoodCounter`.

One solution to this issue could be to invoke `NoGoodCounter#add` from `NogoodRegistry#register(NoGood)` instead of from `NoGoodStoreAlphaRoaming#add`.

Low prio because it only affects statistics.

**Comment by AntoniusW** [comment]
This is interesting and indicates some behaviour I would not have expected. It is correct that (due to #87 ) the ID of a nogood is ignored. However, Alpha should not produce the same nogood twice. What happens here? Is the same nogood derived twice or is there an error in the way `DefaultSolver#addAndBackjumpIfNecessary` is adding it and it simply ends up being added twice?
