### ISSUE TITLE
Naming: "choice" vs. "guess"

### ISSUE THREAD

**Issue by lorenzleutgeb** [alpha-asp/Alpha#85]
I am not aware of any distinction between "choice" and "guess" in our code base and it seems to me that we are using these words interchangeably.

For example, we have methods that are called `guess` but a `ChoiceManager`, "choice points" and a "choice stack".

In order to increase readability/comprehensibility of our code base, I'd like to settle this by preferring one concept over the other.

My personal preference is "guess" ... I like it more because it expresses that we really don't know what the solution(s) will be. Heuristics are also "just" guessing strategies IMO.

**Comment by AntoniusW** [comment]
I guess we can choose either. :-)

Streamlining terminology here is a good idea. Thinking in terms of the heuristics, it seems more correct to name it a "guess", because the heuristics try to guess which assignment makes for an easier search-space exploration. On the other hand, the solver is choosing which assignment to pursue first and it will pursue the other options anyways because we have a complete search procedure. The solver, when making a decision, in that sense is not guessing but choosing one of several options.

To me, `choice` feels a bit more correct, because it describes directly what the solver is doing while `guess` describes more the intended result (to guess for a good search space separation).

**Comment by lorenzleutgeb** [comment]
I'm glad our search space only has two elements...

Let's go for "choice" then, to make it quick and easy!

**Comment by lorenzleutgeb** [comment]
Addressed in 551119dadb13e463bd3ea15f7dc488825ca6d1f1

**Comment by lorenzleutgeb** [comment]
Landed with #83
